# Generated by Django 3.1.7 on 2021-08-03 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predict', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='img',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
